### PR TITLE
17 create initial unit test for tcplfit2

### PR DESCRIPTION
**Pull request by gracezhihuizhao**
Created initial unit tests for modeling fitting functions and core functions. Tests with HTTP and HTTR data have been moved to new tickets, this PR should fulfill this ticket.

### CODE REVIEW

**Comment by kpaulfriedman** [comment]
Hi @gracezhihuizhao and @sedavid01 I was wondering if it would help for Grace to create an RMarkdown report to show how the unit test can be applied/function? This might help with review beyond looking at the code (essentially, an example of running the unit test). Please let me know what you think of that.

**Comment by sedavid01** [comment]
> Hi @gracezhihuizhao and @sedavid01 I was wondering if it would help for Grace to create an RMarkdown report to show how the unit test can be applied/function? This might help with review beyond looking at the code (essentially, an example of running the unit test). Please let me know what you think of that.

@kpaulfriedman, I think this is a good idea and something that I am in support of.  Do you think this ought to be a vignette or a separate Rmd either elsewhere in the package dir or just added to the ticket?  (Hope this follow-up question makes sense.  If not, I am more than happy to clarify.)  Thank you for the suggestion/feedback, @kpaulfriedman.

**Comment by kpaulfriedman** [comment]
@sedavid01 I don't think it needs to be a vignette per se - but something to keep maybe in the tcpl-util or an internal repository (?).

**Comment by sedavid01** [comment]
> @sedavid01 I don't think it needs to be a vignette per se - but something to keep maybe in the tcpl-util or an internal repository (?).

I would agree, just did not necessarily want to rule out the option of a vignette.  I think in 'tcpl-util' may be an appropriate location, but I will coordinate with @brown-jason and @gracezhihuizhao about where to put this Rmd - then make a note of where it lives.  (Note: I will make sure that Grace attaches the Rmd rendering here for easy review.)

Please let me know if you have any further comments, questions, and/or concerns.

**Comment by gracezhihuizhao** [comment]
@kpaulfriedman and @sedavid01 Please see the attached pdf for the markdown report showing how unit test works. The RMarkdown file is still in my local computer, I can push it to remote once we figure out where to store it. Please let me know if you have any questions, concerns or suggestions. Thanks! 
[Unit Test Demo.pdf](https://github.com/USEPA/CompTox-ToxCast-tcplFit2/files/12612887/Unit.Test.Demo.pdf)

**Comment by sedavid01** [comment]
@gracezhihuizhao please see this suggestion from @brown-jason:
check out usethis::use_build_ignore and create a folder called analyses that we can store stuff like this in.  See here: https://stackoverflow.com/questions/13182634/rbuildignore-and-excluding-directories

This should allow us to keep the Rmd you developed for the "unit tests" in the package without balling them up as part of the R package and sending to CRAN.

**Review by sedavid01 — COMMENTED** [review]
The unit test updates looks good overall, with some odd behavior with exp4 and gain-loss which we may need to revisit later.

However, not approving as of now since there should only be 3 commits and 14 files changed between ticket #17 and dev.

**Review by sedavid01 — APPROVED** [review]
The updates in the test directory and files look good.  Additionally the unit tests all pass.  Though there are some "rouge files" in this PR (which seems slightly mysterious) going to approve this PR.

**Pull request merged**
