### PR TITLE
6 update readme on cran

### PR DESCRIPTION
**Pull request by gracezhihuizhao**
Updated README file, archived the old README.

### CODE REVIEW

**Review by sedavid01 — CHANGES_REQUESTED** [review]
There are some comments for minor updates.  Otherwise, overall looks good from my end.

**Review by sedavid01 — APPROVED** [review]
Recent commit incorporated outstanding comments.  Approving this PR.  Before merging, @kpaulfriedman does this mee the needs of the ask?

Note: 'dev' needs to be updated with changes in 'master'.  @brown-jason please note whether it is okay to merge these updates into 'dev' before it is updated or whether the PR should merged after 'dev' is updated from 'master'.

Thanks all!

**Comment by brown-jason** [comment]
@sedavid01 merged with main feel free to squash and merge

**Comment by sedavid01** [comment]
@brown-jason, will this create merge conflicts since this branch and the master branch share certain updates which are not on dev yet?

**Comment by brown-jason** [comment]
> @brown-jason, will this create merge conflicts since this branch and the master branch share certain updates which are not on dev yet?

No I did a merge already with what is on master branch so for now there should be no merge conflicts.

**Review by kpaulfriedman — APPROVED** [review]

**Comment by sedavid01** [comment]
@brown-jason, changes are merged to 'dev' please verify when you get the chance and if any branch clean-up is needed please either do so or provide guidance/instructions. Thanks, -Sarah

**Pull request merged**
